name: PyTorch Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install torch torchvision
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa /" | sudo tee /etc/apt/sources.list.d/cuda.list
        sudo apt-get update
        sudo apt-get -y install cuda

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PyTorch code
      run: python main.py
